name: ayur_flutter_app
description: AyurChain prototype mobile app
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.14.0
  qr_flutter: ^4.0.0
  mobile_scanner: ^2.0.0
  provider: ^6.0.0
